### ISSUE TITLE
dbt found two macros named "synapse__snapshot_merge_sql" in the project   "dbt_synapse".

### ISSUE THREAD

**Issue by nvinhphuc** [dbt-msft/dbt-synapse#81]
Hi guys, I'm new to dbt. I'm trying to run "dbt init" project and edit the profile to my database. I can run the "dbt debug". But when, I run "dbt compile" or "dbt run" it shows this error:
```
Encountered an error:
Compilation Error
  dbt found two macros named "synapse__snapshot_merge_sql" in the project
  "dbt_synapse".
   To fix this error, rename or remove one of the following macros:
      - macros/materializations/snapshots/snapshot_merge.sql
      - macros/materializations/snapshot/snapshot_merge.sql
```

I'm using `dbt-core-1.0.3` `dbt-extractor-0.4.0` `dbt-sqlserver-1.0.0` `dbt-synapse-1.0.1`

**Comment by nvinhphuc** [comment]
It works with dbt-synapse version 1.0.2b1
